[build]
  # Build command for Vite React app
  command = "npm run build"
  # Publish directory (Vite's default output)
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.counterapi.dev; frame-src 'self' https://www.google.com https://maps.google.com https://www.google.com/maps; frame-ancestors 'none';"
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for images
[[headers]]
  for = "/gallery/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for favicon and icons
[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for HTML files (no caching)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Domain configuration
[context.production.environment]
  VITE_SITE_URL = "https://motherlycarechildrenshome.org"

[context.deploy-preview.environment]
  VITE_SITE_URL = "https://deploy-preview-{id}--motherlycarechildrenshome.netlify.app"

[context.branch-deploy.environment]
  VITE_SITE_URL = "https://{branch}--motherlycarechildrenshome.netlify.app"
